const notesData = {
    "ace": {
        "title": "Associate Cloud Engineer (ACE)",
        "pdfs": [
            { "title": "Student Guide Book 1", "file": "pls-academy-ace-student-slides-1-2303.pdf" },
            { "title": "Student Guide Book 2", "file": "pls-academy-ace-student-slides-2-2303.pdf" },
            { "title": "Student Guide Book 3", "file": "pls-academy-ace-student-slides-3-2303.pdf" },
            { "title": "Student Guide Book 4", "file": "pls-academy-ace-student-slides-4-2303.pdf" },
            { "title": "Student Guide Book 5", "file": "pls-academy-ace-student-slides-5-2303.pdf" },
            { "title": "Student Guide Book 6", "file": "pls-academy-ace-student-slides-6-2303.pdf" },
            { "title": "Student Guide Book 7", "file": "exam-readyness.pdf" },
            { "header": "Below notes are for Data Warehouse Session:" },
            { "title": "M0 Course Introduction", "file": "[PTI-PWDW-A]_M0_Course_Introduction.pdf" },
            { "title": "M1 Data Warehouse Solutions", "file": "[PTI-PWDW-A]_M1_Data_Warehouse_Solutions_on_Google_Cloud.pdf" },
            { "title": "M2 BigQuery for Data Warehousing", "file": "[PTI-PWDW-A]_M2_BigQuery_for_Data_Warehousing_Professionals.pdf" },
            { "title": "M3 Migrating to BigQuery", "file": "[PTI-PWDW-A]_M3_Migrating_to_BigQuery.pdf" },
            { "title": "M4 ETL Tools and Positioning", "file": "[PTI-PWDW-A]_M4_ETL_Tools_and_Positioning.pdf" },
            { "title": "M5 Streaming Analytics", "file": "[PTI-PWDW-A]_M5_Streaming_Analytics.pdf" },
            { "title": "M6 Introduction to Looker", "file": "[PTI-PWDW-A]_M6_Introduction_to_Looker_as_a_Data_Platform.pdf" },
            { "title": "M7 BigQuery Extended Capabilities", "file": "[PTI-PWDW-A]_M7_BigQuery_Extended_Capabilities.pdf" },
            { "header": "Below notes are for Apigee API Platform Session Managing Google Cloud's Apigee API Platform for Hybrid Cloud: Lecture Notes :" },
            { "title": "M0 Welcome to Apigee API Platform", "file": "M0_Welcome_to_Managing_Google_Cloud's_Apigee_API_Platform_for_Hybrid_Cloud.pdf" },
            { "title": "M1 Fundamentals", "file": "M1_Fundamentals.pdf" },
            { "title": "M2 Architecture", "file": "M2_Architecture.pdf" },
            { "title": "M3 Installation and Platform Operation", "file": "M3_Installation_and_Platform_Operation.pdf" },
            { "title": "M4 Deployment and Environment Management", "file": "M4_Deployment_and_Environment_Management.pdf" },
            { "title": "M5 Security", "file": "M5_Security.pdf" },
            { "title": "M6 Capacity Planning and Scaling", "file": "M6_Capacity_Planning_and_Scaling.pdf" },
            { "title": "M7 Upgrade", "file": "M7_Upgrade.pdf" },
            { "title": "M8 Logging and Monitoring", "file": "M8_Logging_and_Monitoring.pdf" },
            { "header": "Below notes are forBuild with Vertex AI Skill Badge Sessions: Lecture Notes" },

            { "title": "Session1 ", "file": "firestore.pdf" },
            { "header": "Below notes are for Google Workspace - Work Transformation Session:" },
            { "title": "Course Introduction", "file": "Students_[PTI-PWWT-A] Course Introduction.pdf" },
            { "title": "M1 Google Workspace Customer Success Methodology", "file": "Students_[PTI-PWWT-A] M1 - Google Workspace Customer Success Methodology.pdf" },
            { "title": "M2 Provisioning", "file": "Students_[PTI-PWWT-A] M2 - Provisioning.pdf" },
            { "title": "M2.1 Lab Environment", "file": "Students_[PTI-PWWT-A] M2.1 Lab Environment - Deck.pdf" },
            { "title": "M3 System Access and Authentication", "file": "Students_[PTI-PWWT-A] M3 - System Access and Authentication.pdf" },
            { "title": "M4 Mail Routing", "file": "Students_[PTI-PWWT-A] M4 - Mail Routing.pdf" },
            { "title": "M5 Migration", "file": "Students_[PTI-PWWT-A] M5 - Migration.pdf" },
            { "title": "M6 Coexistence", "file": "Students_[PTI-PWWT-A] M6 - Coexistence.pdf" },
            { "title": "M7 Enterprise Security Overview", "file": "Students_[PTI-PWWT-A] M7 - Enterprise Security Overview.pdf" },
            { "title": "M8 Work Transformation Summary", "file": "Students_[PTI-PWWT-A] M8 - Work Transformation summary.pdf" },
            { "header": "Below notes are for Design and Manage Oracle Workloads on Google Cloud Session:" },
            { "title": "M0 Course Introduction", "file": "Delivery Copy M0_ Course Introduction (2).pdf" },
            { "title": "M2 Managed and integrated Oracle Services", "file": "Delivery Copy M2_ Managed and integrated Oracle Services.pdf" },
            { "title": "M3 Architecting Oracle solutions", "file": "Delivery Copy of M3_ Architecting Oracle solutions.pdf" },
            { "title": "M5 Design and Manage Oracle Workloads Demo", "file": "Delivery Copy of M5_ Design and Manage Oracle Workloads on Google Cloud Demo.pdf" },
            { "title": "M5 Vertex AI Coffee Demo - Hands-On Lab Guide", "file": "Delivery copy of Design and Manage Oracle Workloads on Google Cloud M5 Vertex AI Coffee Demo - Hands-On Lab Guide.pdf" },
            { "title": "M6 Resources and Q&A", "file": "Delivery Copy of M6_ Resources and Q&A (2).pdf" }

            ,
            { "header": "Below notes are for Develop apps with Conversational Agents: Lecture Notes" },
            { "title": "M0 Course Introduction", "file": "Copy of M0_ Course introduction v1.2.pdf" },
            { "title": "M1 Conversational Agents Overview", "file": "Copy of M1_ Conversational Agents overview v1.2.pdf" },
            { "title": "M2 Generative Playbooks", "file": "Copy of M2_ Generative Playbooks v1.2.pdf" },
            { "title": "M3 Virtual FAQ with data store agents", "file": "Copy of M3_ Virtual FAQ with data store agents v1.2.pdf" },
            { "title": "M4 Incorporate Generative Features", "file": "Copy of M4_ Incorporate generative features into Conversational Agent Flows v1.2.pdf" },
            { "title": "M5 Production-ready Conversational Agents", "file": "Copy of M5_ Production-ready Conversational Agents v1.2.pdf" }
        ]
    },
    "pca": {
        "title": "Professional Cloud Architect (PCA)",
        "pdfs": [
            { "title": "Student Guide Book 1", "file": "pls-academy-pca-student-slides-1-2301.pdf" },
            { "title": "Student Guide Book 2", "file": "pls-academy-pca-student-slides-2-2301.pdf" },
            { "title": "Student Guide Book 3", "file": "pls-academy-pca-student-slides-3-2301.pdf" },
            { "title": "Student Guide Book 4", "file": "pls-academy-pca-student-slides-4-2301.pdf" },
            { "title": "Student Guide Book 5", "file": "pls-academy-pca-student-slides-5-2301.pdf" },
            { "title": "Student Guide Book 6", "file": "pls-academy-pca-student-slides-6-2301.pdf" },
            { "header": "Below notes are for Data Warehouse Session:" },
            { "title": "M0 Course Introduction", "file": "[PTI-PWDW-A]_M0_Course_Introduction.pdf" },
            { "title": "M1 Data Warehouse Solutions", "file": "[PTI-PWDW-A]_M1_Data_Warehouse_Solutions_on_Google_Cloud.pdf" },
            { "title": "M2 BigQuery for Data Warehousing", "file": "[PTI-PWDW-A]_M2_BigQuery_for_Data_Warehousing_Professionals.pdf" },
            { "title": "M3 Migrating to BigQuery", "file": "[PTI-PWDW-A]_M3_Migrating_to_BigQuery.pdf" },
            { "title": "M4 ETL Tools and Positioning", "file": "[PTI-PWDW-A]_M4_ETL_Tools_and_Positioning.pdf" },
            { "title": "M5 Streaming Analytics", "file": "[PTI-PWDW-A]_M5_Streaming_Analytics.pdf" },
            { "title": "M6 Introduction to Looker", "file": "[PTI-PWDW-A]_M6_Introduction_to_Looker_as_a_Data_Platform.pdf" },
            { "title": "M7 BigQuery Extended Capabilities", "file": "[PTI-PWDW-A]_M7_BigQuery_Extended_Capabilities.pdf" },
            { "header": "Below notes are for Apigee API Platform Session:" },
            { "title": "M0 Welcome to Apigee API Platform", "file": "M0_Welcome_to_Managing_Google_Cloud's_Apigee_API_Platform_for_Hybrid_Cloud.pdf" },
            { "title": "M1 Fundamentals", "file": "M1_Fundamentals.pdf" },
            { "title": "M2 Architecture", "file": "M2_Architecture.pdf" },
            { "title": "M3 Installation and Platform Operation", "file": "M3_Installation_and_Platform_Operation.pdf" },
            { "title": "M4 Deployment and Environment Management", "file": "M4_Deployment_and_Environment_Management.pdf" },
            { "title": "M5 Security", "file": "M5_Security.pdf" },
            { "title": "M6 Capacity Planning and Scaling", "file": "M6_Capacity_Planning_and_Scaling.pdf" },
            { "title": "M7 Upgrade", "file": "M7_Upgrade.pdf" },
            { "title": "M8 Logging and Monitoring", "file": "M8_Logging_and_Monitoring.pdf" },
            { "header": "Below notes are for Google Workspace - Work Transformation Session:" },
            { "title": "Course Introduction", "file": "Students_[PTI-PWWT-A] Course Introduction.pdf" },
            { "title": "M1 Google Workspace Customer Success Methodology", "file": "Students_[PTI-PWWT-A] M1 - Google Workspace Customer Success Methodology.pdf" },
            { "title": "M2 Provisioning", "file": "Students_[PTI-PWWT-A] M2 - Provisioning.pdf" },
            { "title": "M2.1 Lab Environment", "file": "Students_[PTI-PWWT-A] M2.1 Lab Environment - Deck.pdf" },
            { "title": "M3 System Access and Authentication", "file": "Students_[PTI-PWWT-A] M3 - System Access and Authentication.pdf" },
            { "title": "M4 Mail Routing", "file": "Students_[PTI-PWWT-A] M4 - Mail Routing.pdf" },
            { "title": "M5 Migration", "file": "Students_[PTI-PWWT-A] M5 - Migration.pdf" },
            { "title": "M6 Coexistence", "file": "Students_[PTI-PWWT-A] M6 - Coexistence.pdf" },
            { "title": "M7 Enterprise Security Overview", "file": "Students_[PTI-PWWT-A] M7 - Enterprise Security Overview.pdf" },
            { "title": "M8 Work Transformation Summary", "file": "Students_[PTI-PWWT-A] M8 - Work Transformation summary.pdf" },
            { "header": "Below notes are for Design and Manage Oracle Workloads on Google Cloud Session:" },
            { "title": "M0 Course Introduction", "file": "Delivery Copy M0_ Course Introduction (2).pdf" },
            { "title": "M2 Managed and integrated Oracle Services", "file": "Delivery Copy M2_ Managed and integrated Oracle Services.pdf" },
            { "title": "M3 Architecting Oracle solutions", "file": "Delivery Copy of M3_ Architecting Oracle solutions.pdf" },
            { "title": "M5 Design and Manage Oracle Workloads Demo", "file": "Delivery Copy of M5_ Design and Manage Oracle Workloads on Google Cloud Demo.pdf" },
            { "title": "M5 Vertex AI Coffee Demo - Hands-On Lab Guide", "file": "Delivery copy of Design and Manage Oracle Workloads on Google Cloud M5 Vertex AI Coffee Demo - Hands-On Lab Guide.pdf" },
            { "title": "M6 Resources and Q&A", "file": "Delivery Copy of M6_ Resources and Q&A (2).pdf" }
            ,
            { "header": "Below notes are for Develop apps with Conversational Agents: Lecture Notes" },
            { "title": "M0 Course Introduction", "file": "Copy of M0_ Course introduction v1.2.pdf" },
            { "title": "M1 Conversational Agents Overview", "file": "Copy of M1_ Conversational Agents overview v1.2.pdf" },
            { "title": "M2 Generative Playbooks", "file": "Copy of M2_ Generative Playbooks v1.2.pdf" },
            { "title": "M3 Virtual FAQ with data store agents", "file": "Copy of M3_ Virtual FAQ with data store agents v1.2.pdf" },
            { "title": "M4 Incorporate Generative Features", "file": "Copy of M4_ Incorporate generative features into Conversational Agent Flows v1.2.pdf" },
            { "title": "M5 Production-ready Conversational Agents", "file": "Copy of M5_ Production-ready Conversational Agents v1.2.pdf" }
        ]
    },
    "devops": {
        "title": "Professional Cloud DevOps Engineer",
        "pdfs": [
            { "title": "Student Guide Book 1", "file": "pls-academy-pcde-student-slides-1-2307.pdf" },
            { "title": "Student Guide Book 2", "file": "pls-academy-pcde-student-slides-2-2307.pdf" },
            { "title": "Student Guide Book 3", "file": "pls-academy-pcde-student-slides-3-2307.pdf" },
            { "title": "Student Guide Book 4", "file": "pls-academy-pcde-student-slides-4-2307.pdf" },
            { "title": "Student Guide Book 5", "file": "pls-academy-pcde-student-slides-5-2307.pdf" },
            { "title": "Student Guide Book 6", "file": "pls-academy-pcde-student-slides-6-2307.pdf" },
            { "header": "Below notes are for Data Warehouse Session:" },
            { "title": "M0 Course Introduction", "file": "[PTI-PWDW-A]_M0_Course_Introduction.pdf" },
            { "title": "M1 Data Warehouse Solutions", "file": "[PTI-PWDW-A]_M1_Data_Warehouse_Solutions_on_Google_Cloud.pdf" },
            { "title": "M2 BigQuery for Data Warehousing", "file": "[PTI-PWDW-A]_M2_BigQuery_for_Data_Warehousing_Professionals.pdf" },
            { "title": "M3 Migrating to BigQuery", "file": "[PTI-PWDW-A]_M3_Migrating_to_BigQuery.pdf" },
            { "title": "M4 ETL Tools and Positioning", "file": "[PTI-PWDW-A]_M4_ETL_Tools_and_Positioning.pdf" },
            { "title": "M5 Streaming Analytics", "file": "[PTI-PWDW-A]_M5_Streaming_Analytics.pdf" },
            { "title": "M6 Introduction to Looker", "file": "[PTI-PWDW-A]_M6_Introduction_to_Looker_as_a_Data_Platform.pdf" },
            { "title": "M7 BigQuery Extended Capabilities", "file": "[PTI-PWDW-A]_M7_BigQuery_Extended_Capabilities.pdf" },
            { "header": "Below notes are for Apigee API Platform Session:" },
            { "title": "M0 Welcome to Apigee API Platform", "file": "M0_Welcome_to_Managing_Google_Cloud's_Apigee_API_Platform_for_Hybrid_Cloud.pdf" },
            { "title": "M1 Fundamentals", "file": "M1_Fundamentals.pdf" },
            { "title": "M2 Architecture", "file": "M2_Architecture.pdf" },
            { "title": "M3 Installation and Platform Operation", "file": "M3_Installation_and_Platform_Operation.pdf" },
            { "title": "M4 Deployment and Environment Management", "file": "M4_Deployment_and_Environment_Management.pdf" },
            { "title": "M5 Security", "file": "M5_Security.pdf" },
            { "title": "M6 Capacity Planning and Scaling", "file": "M6_Capacity_Planning_and_Scaling.pdf" },
            { "title": "M7 Upgrade", "file": "M7_Upgrade.pdf" },
            { "title": "M8 Logging and Monitoring", "file": "M8_Logging_and_Monitoring.pdf" },
            { "header": "Below notes are for Google Workspace - Work Transformation Session:" },
            { "title": "Course Introduction", "file": "Students_[PTI-PWWT-A] Course Introduction.pdf" },
            { "title": "M1 Google Workspace Customer Success Methodology", "file": "Students_[PTI-PWWT-A] M1 - Google Workspace Customer Success Methodology.pdf" },
            { "title": "M2 Provisioning", "file": "Students_[PTI-PWWT-A] M2 - Provisioning.pdf" },
            { "title": "M2.1 Lab Environment", "file": "Students_[PTI-PWWT-A] M2.1 Lab Environment - Deck.pdf" },
            { "title": "M3 System Access and Authentication", "file": "Students_[PTI-PWWT-A] M3 - System Access and Authentication.pdf" },
            { "title": "M4 Mail Routing", "file": "Students_[PTI-PWWT-A] M4 - Mail Routing.pdf" },
            { "title": "M5 Migration", "file": "Students_[PTI-PWWT-A] M5 - Migration.pdf" },
            { "title": "M6 Coexistence", "file": "Students_[PTI-PWWT-A] M6 - Coexistence.pdf" },
            { "title": "M7 Enterprise Security Overview", "file": "Students_[PTI-PWWT-A] M7 - Enterprise Security Overview.pdf" },
            { "title": "M8 Work Transformation Summary", "file": "Students_[PTI-PWWT-A] M8 - Work Transformation summary.pdf" },
            { "header": "Below notes are for Design and Manage Oracle Workloads on Google Cloud Session:" },
            { "title": "M0 Course Introduction", "file": "Delivery Copy M0_ Course Introduction (2).pdf" },
            { "title": "M2 Managed and integrated Oracle Services", "file": "Delivery Copy M2_ Managed and integrated Oracle Services.pdf" },
            { "title": "M3 Architecting Oracle solutions", "file": "Delivery Copy of M3_ Architecting Oracle solutions.pdf" },
            { "title": "M5 Design and Manage Oracle Workloads Demo", "file": "Delivery Copy of M5_ Design and Manage Oracle Workloads on Google Cloud Demo.pdf" },
            { "title": "M5 Vertex AI Coffee Demo - Hands-On Lab Guide", "file": "Delivery copy of Design and Manage Oracle Workloads on Google Cloud M5 Vertex AI Coffee Demo - Hands-On Lab Guide.pdf" },
            { "title": "M6 Resources and Q&A", "file": "Delivery Copy of M6_ Resources and Q&A (2).pdf" }
            ,
            { "header": "Below notes are for Develop apps with Conversational Agents: Lecture Notes" },
            { "title": "M0 Course Introduction", "file": "Copy of M0_ Course introduction v1.2.pdf" },
            { "title": "M1 Conversational Agents Overview", "file": "Copy of M1_ Conversational Agents overview v1.2.pdf" },
            { "title": "M2 Generative Playbooks", "file": "Copy of M2_ Generative Playbooks v1.2.pdf" },
            { "title": "M3 Virtual FAQ with data store agents", "file": "Copy of M3_ Virtual FAQ with data store agents v1.2.pdf" },
            { "title": "M4 Incorporate Generative Features", "file": "Copy of M4_ Incorporate generative features into Conversational Agent Flows v1.2.pdf" },
            { "title": "M5 Production-ready Conversational Agents", "file": "Copy of M5_ Production-ready Conversational Agents v1.2.pdf" }
        ]
    },
    "data-engineer": {
        "title": "Professional Data Engineer",
        "pdfs": [
            { "title": "Student Guide Book 1", "file": "pde1.pdf" },
            { "title": "Student Guide Book 2", "file": "pde2.pdf" },
            { "title": "Student Guide Book 3", "file": "pde3.pdf" },
            { "title": "Student Guide Book 4", "file": "pde4.pdf" },
            { "title": "Student Guide Book 5", "file": "pde5.pdf" },
            { "title": "Student Guide Book 6", "file": "pde6.pdf" },
            { "title": "Student Guide Book 7", "file": "pde7.pdf" },
            { "title": "Additional Notes (PDE 1)", "file": "pde-1.pdf" },
            { "header": "Below notes are for Data Warehouse Session:" },
            { "title": "M0 Course Introduction", "file": "[PTI-PWDW-A]_M0_Course_Introduction.pdf" },
            { "title": "M1 Data Warehouse Solutions", "file": "[PTI-PWDW-A]_M1_Data_Warehouse_Solutions_on_Google_Cloud.pdf" },
            { "title": "M2 BigQuery for Data Warehousing", "file": "[PTI-PWDW-A]_M2_BigQuery_for_Data_Warehousing_Professionals.pdf" },
            { "title": "M3 Migrating to BigQuery", "file": "[PTI-PWDW-A]_M3_Migrating_to_BigQuery.pdf" },
            { "title": "M4 ETL Tools and Positioning", "file": "[PTI-PWDW-A]_M4_ETL_Tools_and_Positioning.pdf" },
            { "title": "M5 Streaming Analytics", "file": "[PTI-PWDW-A]_M5_Streaming_Analytics.pdf" },
            { "title": "M6 Introduction to Looker", "file": "[PTI-PWDW-A]_M6_Introduction_to_Looker_as_a_Data_Platform.pdf" },
            { "title": "M7 BigQuery Extended Capabilities", "file": "[PTI-PWDW-A]_M7_BigQuery_Extended_Capabilities.pdf" },
            { "header": "Below notes are for Apigee API Platform Session:" },
            { "title": "M0 Welcome to Apigee API Platform", "file": "M0_Welcome_to_Managing_Google_Cloud's_Apigee_API_Platform_for_Hybrid_Cloud.pdf" },
            { "title": "M1 Fundamentals", "file": "M1_Fundamentals.pdf" },
            { "title": "M2 Architecture", "file": "M2_Architecture.pdf" },
            { "title": "M3 Installation and Platform Operation", "file": "M3_Installation_and_Platform_Operation.pdf" },
            { "title": "M4 Deployment and Environment Management", "file": "M4_Deployment_and_Environment_Management.pdf" },
            { "title": "M5 Security", "file": "M5_Security.pdf" },
            { "title": "M6 Capacity Planning and Scaling", "file": "M6_Capacity_Planning_and_Scaling.pdf" },
            { "title": "M7 Upgrade", "file": "M7_Upgrade.pdf" },
            { "title": "M8 Logging and Monitoring", "file": "M8_Logging_and_Monitoring.pdf" },
            { "header": "Below notes are for Google Workspace - Work Transformation Session:" },
            { "title": "Course Introduction", "file": "Students_[PTI-PWWT-A] Course Introduction.pdf" },
            { "title": "M1 Google Workspace Customer Success Methodology", "file": "Students_[PTI-PWWT-A] M1 - Google Workspace Customer Success Methodology.pdf" },
            { "title": "M2 Provisioning", "file": "Students_[PTI-PWWT-A] M2 - Provisioning.pdf" },
            { "title": "M2.1 Lab Environment", "file": "Students_[PTI-PWWT-A] M2.1 Lab Environment - Deck.pdf" },
            { "title": "M3 System Access and Authentication", "file": "Students_[PTI-PWWT-A] M3 - System Access and Authentication.pdf" },
            { "title": "M4 Mail Routing", "file": "Students_[PTI-PWWT-A] M4 - Mail Routing.pdf" },
            { "title": "M5 Migration", "file": "Students_[PTI-PWWT-A] M5 - Migration.pdf" },
            { "title": "M6 Coexistence", "file": "Students_[PTI-PWWT-A] M6 - Coexistence.pdf" },
            { "title": "M7 Enterprise Security Overview", "file": "Students_[PTI-PWWT-A] M7 - Enterprise Security Overview.pdf" },
            { "title": "M8 Work Transformation Summary", "file": "Students_[PTI-PWWT-A] M8 - Work Transformation summary.pdf" },
            { "header": "Below notes are for Design and Manage Oracle Workloads on Google Cloud Session:" },
            { "title": "M0 Course Introduction", "file": "Delivery Copy M0_ Course Introduction (2).pdf" },
            { "title": "M2 Managed and integrated Oracle Services", "file": "Delivery Copy M2_ Managed and integrated Oracle Services.pdf" },
            { "title": "M3 Architecting Oracle solutions", "file": "Delivery Copy of M3_ Architecting Oracle solutions.pdf" },
            { "title": "M5 Design and Manage Oracle Workloads Demo", "file": "Delivery Copy of M5_ Design and Manage Oracle Workloads on Google Cloud Demo.pdf" },
            { "title": "M5 Vertex AI Coffee Demo - Hands-On Lab Guide", "file": "Delivery copy of Design and Manage Oracle Workloads on Google Cloud M5 Vertex AI Coffee Demo - Hands-On Lab Guide.pdf" },
            { "title": "M6 Resources and Q&A", "file": "Delivery Copy of M6_ Resources and Q&A (2).pdf" }
            ,
            { "header": "Below notes are for Develop apps with Conversational Agents: Lecture Notes" },
            { "title": "M0 Course Introduction", "file": "Copy of M0_ Course introduction v1.2.pdf" },
            { "title": "M1 Conversational Agents Overview", "file": "Copy of M1_ Conversational Agents overview v1.2.pdf" },
            { "title": "M2 Generative Playbooks", "file": "Copy of M2_ Generative Playbooks v1.2.pdf" },
            { "title": "M3 Virtual FAQ with data store agents", "file": "Copy of M3_ Virtual FAQ with data store agents v1.2.pdf" },
            { "title": "M4 Incorporate Generative Features", "file": "Copy of M4_ Incorporate generative features into Conversational Agent Flows v1.2.pdf" },
            { "title": "M5 Production-ready Conversational Agents", "file": "Copy of M5_ Production-ready Conversational Agents v1.2.pdf" }
        ]
    },
    "security": {
        "title": "Professional Cloud Security Engineer",
        "pdfs": [
            { "title": "Session 1", "file": "2303_2411_PCSE Session 1.pdf" },
            { "title": "Sessions 2 and 3", "file": "2-3.pdf" },
            { "title": "Sessions 4 and 5", "file": "2302_2411_PCSE Sessions 4 and 5_Students.pdf" },
            { "title": "Sessions 6 and 7", "file": "6-7.pdf" },
            { "title": "Sessions 8 and 9", "file": "8-9.pdf" },
            { "title": "Sessions 10 and 11", "file": "10-11.pdf" },
            { "header": "Below notes are for Data Warehouse Session:" },
            { "title": "M0 Course Introduction", "file": "[PTI-PWDW-A]_M0_Course_Introduction.pdf" },
            { "title": "M1 Data Warehouse Solutions", "file": "[PTI-PWDW-A]_M1_Data_Warehouse_Solutions_on_Google_Cloud.pdf" },
            { "title": "M2 BigQuery for Data Warehousing", "file": "[PTI-PWDW-A]_M2_BigQuery_for_Data_Warehousing_Professionals.pdf" },
            { "title": "M3 Migrating to BigQuery", "file": "[PTI-PWDW-A]_M3_Migrating_to_BigQuery.pdf" },
            { "title": "M4 ETL Tools and Positioning", "file": "[PTI-PWDW-A]_M4_ETL_Tools_and_Positioning.pdf" },
            { "title": "M5 Streaming Analytics", "file": "[PTI-PWDW-A]_M5_Streaming_Analytics.pdf" },
            { "title": "M6 Introduction to Looker", "file": "[PTI-PWDW-A]_M6_Introduction_to_Looker_as_a_Data_Platform.pdf" },
            { "title": "M7 BigQuery Extended Capabilities", "file": "[PTI-PWDW-A]_M7_BigQuery_Extended_Capabilities.pdf" },
            { "header": "Below notes are for Apigee API Platform Session:" },
            { "title": "M0 Welcome to Apigee API Platform", "file": "M0_Welcome_to_Managing_Google_Cloud's_Apigee_API_Platform_for_Hybrid_Cloud.pdf" },
            { "title": "M1 Fundamentals", "file": "M1_Fundamentals.pdf" },
            { "title": "M2 Architecture", "file": "M2_Architecture.pdf" },
            { "title": "M3 Installation and Platform Operation", "file": "M3_Installation_and_Platform_Operation.pdf" },
            { "title": "M4 Deployment and Environment Management", "file": "M4_Deployment_and_Environment_Management.pdf" },
            { "title": "M5 Security", "file": "M5_Security.pdf" },
            { "title": "M6 Capacity Planning and Scaling", "file": "M6_Capacity_Planning_and_Scaling.pdf" },
            { "title": "M7 Upgrade", "file": "M7_Upgrade.pdf" },
            { "title": "M8 Logging and Monitoring", "file": "M8_Logging_and_Monitoring.pdf" },
            { "header": "Below notes are for Google Workspace - Work Transformation Session:" },
            { "title": "Course Introduction", "file": "Students_[PTI-PWWT-A] Course Introduction.pdf" },
            { "title": "M1 Google Workspace Customer Success Methodology", "file": "Students_[PTI-PWWT-A] M1 - Google Workspace Customer Success Methodology.pdf" },
            { "title": "M2 Provisioning", "file": "Students_[PTI-PWWT-A] M2 - Provisioning.pdf" },
            { "title": "M2.1 Lab Environment", "file": "Students_[PTI-PWWT-A] M2.1 Lab Environment - Deck.pdf" },
            { "title": "M3 System Access and Authentication", "file": "Students_[PTI-PWWT-A] M3 - System Access and Authentication.pdf" },
            { "title": "M4 Mail Routing", "file": "Students_[PTI-PWWT-A] M4 - Mail Routing.pdf" },
            { "title": "M5 Migration", "file": "Students_[PTI-PWWT-A] M5 - Migration.pdf" },
            { "title": "M6 Coexistence", "file": "Students_[PTI-PWWT-A] M6 - Coexistence.pdf" },
            { "title": "M7 Enterprise Security Overview", "file": "Students_[PTI-PWWT-A] M7 - Enterprise Security Overview.pdf" },
            { "title": "M8 Work Transformation Summary", "file": "Students_[PTI-PWWT-A] M8 - Work Transformation summary.pdf" },
            { "header": "Below notes are for Design and Manage Oracle Workloads on Google Cloud Session:" },
            { "title": "M0 Course Introduction", "file": "Delivery Copy M0_ Course Introduction (2).pdf" },
            { "title": "M2 Managed and integrated Oracle Services", "file": "Delivery Copy M2_ Managed and integrated Oracle Services.pdf" },
            { "title": "M3 Architecting Oracle solutions", "file": "Delivery Copy of M3_ Architecting Oracle solutions.pdf" },
            { "title": "M5 Design and Manage Oracle Workloads Demo", "file": "Delivery Copy of M5_ Design and Manage Oracle Workloads on Google Cloud Demo.pdf" },
            { "title": "M5 Vertex AI Coffee Demo - Hands-On Lab Guide", "file": "Delivery copy of Design and Manage Oracle Workloads on Google Cloud M5 Vertex AI Coffee Demo - Hands-On Lab Guide.pdf" },
            { "title": "M6 Resources and Q&A", "file": "Delivery Copy of M6_ Resources and Q&A (2).pdf" }
            ,
            { "header": "Below notes are for Develop apps with Conversational Agents: Lecture Notes" },
            { "title": "M0 Course Introduction", "file": "Copy of M0_ Course introduction v1.2.pdf" },
            { "title": "M1 Conversational Agents Overview", "file": "Copy of M1_ Conversational Agents overview v1.2.pdf" },
            { "title": "M2 Generative Playbooks", "file": "Copy of M2_ Generative Playbooks v1.2.pdf" },
            { "title": "M3 Virtual FAQ with data store agents", "file": "Copy of M3_ Virtual FAQ with data store agents v1.2.pdf" },
            { "title": "M4 Incorporate Generative Features", "file": "Copy of M4_ Incorporate generative features into Conversational Agent Flows v1.2.pdf" },
            { "title": "M5 Production-ready Conversational Agents", "file": "Copy of M5_ Production-ready Conversational Agents v1.2.pdf" }
        ]
    },
    "network": {
        "title": "Professional Cloud Network Engineer",
        "pdfs": [
            { "title": "Student Guide Book 1", "file": "network-1.pdf" },
            { "title": "Student Guide Book 2", "file": "network-2.pdf" },
            { "title": "Student Guide Book 3", "file": "network-3.pdf" },
            { "title": "Student Guide Book 4", "file": "network-4.pdf" },
            { "title": "Student Guide Book 5", "file": "network-5.pdf" },
            { "title": "Student Guide Book 6", "file": "network-6.pdf" },
            { "header": "Below notes are for Data Warehouse Session:" },
            { "title": "M0 Course Introduction", "file": "[PTI-PWDW-A]_M0_Course_Introduction.pdf" },
            { "title": "M1 Data Warehouse Solutions", "file": "[PTI-PWDW-A]_M1_Data_Warehouse_Solutions_on_Google_Cloud.pdf" },
            { "title": "M2 BigQuery for Data Warehousing", "file": "[PTI-PWDW-A]_M2_BigQuery_for_Data_Warehousing_Professionals.pdf" },
            { "title": "M3 Migrating to BigQuery", "file": "[PTI-PWDW-A]_M3_Migrating_to_BigQuery.pdf" },
            { "title": "M4 ETL Tools and Positioning", "file": "[PTI-PWDW-A]_M4_ETL_Tools_and_Positioning.pdf" },
            { "title": "M5 Streaming Analytics", "file": "[PTI-PWDW-A]_M5_Streaming_Analytics.pdf" },
            { "title": "M6 Introduction to Looker", "file": "[PTI-PWDW-A]_M6_Introduction_to_Looker_as_a_Data_Platform.pdf" },
            { "title": "M7 BigQuery Extended Capabilities", "file": "[PTI-PWDW-A]_M7_BigQuery_Extended_Capabilities.pdf" },
            { "header": "Below notes are for Apigee API Platform Session:" },
            { "title": "M0 Welcome to Apigee API Platform", "file": "M0_Welcome_to_Managing_Google_Cloud's_Apigee_API_Platform_for_Hybrid_Cloud.pdf" },
            { "title": "M1 Fundamentals", "file": "M1_Fundamentals.pdf" },
            { "title": "M2 Architecture", "file": "M2_Architecture.pdf" },
            { "title": "M3 Installation and Platform Operation", "file": "M3_Installation_and_Platform_Operation.pdf" },
            { "title": "M4 Deployment and Environment Management", "file": "M4_Deployment_and_Environment_Management.pdf" },
            { "title": "M5 Security", "file": "M5_Security.pdf" },
            { "title": "M6 Capacity Planning and Scaling", "file": "M6_Capacity_Planning_and_Scaling.pdf" },
            { "title": "M7 Upgrade", "file": "M7_Upgrade.pdf" },
            { "title": "M8 Logging and Monitoring", "file": "M8_Logging_and_Monitoring.pdf" },
            { "header": "Below notes are for Google Workspace - Work Transformation Session:" },
            { "title": "Course Introduction", "file": "Students_[PTI-PWWT-A] Course Introduction.pdf" },
            { "title": "M1 Google Workspace Customer Success Methodology", "file": "Students_[PTI-PWWT-A] M1 - Google Workspace Customer Success Methodology.pdf" },
            { "title": "M2 Provisioning", "file": "Students_[PTI-PWWT-A] M2 - Provisioning.pdf" },
            { "title": "M2.1 Lab Environment", "file": "Students_[PTI-PWWT-A] M2.1 Lab Environment - Deck.pdf" },
            { "title": "M3 System Access and Authentication", "file": "Students_[PTI-PWWT-A] M3 - System Access and Authentication.pdf" },
            { "title": "M4 Mail Routing", "file": "Students_[PTI-PWWT-A] M4 - Mail Routing.pdf" },
            { "title": "M5 Migration", "file": "Students_[PTI-PWWT-A] M5 - Migration.pdf" },
            { "title": "M6 Coexistence", "file": "Students_[PTI-PWWT-A] M6 - Coexistence.pdf" },
            { "title": "M7 Enterprise Security Overview", "file": "Students_[PTI-PWWT-A] M7 - Enterprise Security Overview.pdf" },
            { "title": "M8 Work Transformation Summary", "file": "Students_[PTI-PWWT-A] M8 - Work Transformation summary.pdf" },
            { "header": "Below notes are for Design and Manage Oracle Workloads on Google Cloud Session:" },
            { "title": "M0 Course Introduction", "file": "Delivery Copy M0_ Course Introduction (2).pdf" },
            { "title": "M2 Managed and integrated Oracle Services", "file": "Delivery Copy M2_ Managed and integrated Oracle Services.pdf" },
            { "title": "M3 Architecting Oracle solutions", "file": "Delivery Copy of M3_ Architecting Oracle solutions.pdf" },
            { "title": "M5 Design and Manage Oracle Workloads Demo", "file": "Delivery Copy of M5_ Design and Manage Oracle Workloads on Google Cloud Demo.pdf" },
            { "title": "M5 Vertex AI Coffee Demo - Hands-On Lab Guide", "file": "Delivery copy of Design and Manage Oracle Workloads on Google Cloud M5 Vertex AI Coffee Demo - Hands-On Lab Guide.pdf" },
            { "title": "M6 Resources and Q&A", "file": "Delivery Copy of M6_ Resources and Q&A (2).pdf" }
            ,
            { "header": "Below notes are for Develop apps with Conversational Agents: Lecture Notes" },
            { "title": "M0 Course Introduction", "file": "Copy of M0_ Course introduction v1.2.pdf" },
            { "title": "M1 Conversational Agents Overview", "file": "Copy of M1_ Conversational Agents overview v1.2.pdf" },
            { "title": "M2 Generative Playbooks", "file": "Copy of M2_ Generative Playbooks v1.2.pdf" },
            { "title": "M3 Virtual FAQ with data store agents", "file": "Copy of M3_ Virtual FAQ with data store agents v1.2.pdf" },
            { "title": "M4 Incorporate Generative Features", "file": "Copy of M4_ Incorporate generative features into Conversational Agent Flows v1.2.pdf" },
            { "title": "M5 Production-ready Conversational Agents", "file": "Copy of M5_ Production-ready Conversational Agents v1.2.pdf" }
        ]
    },
    "digital-leader": {
        "title": "Cloud Digital Leader",
        "pdfs": [
            { "title": "Student Guide Book 1", "file": "pls-academy-cld-student-v2-slides-1.pdf" },
            { "title": "Student Guide Book 2", "file": "pls-academy-cld-student-v2-slides-2.pdf" },
            { "title": "Student Guide Book 3", "file": "pls-academy-cld-student-v2-slides-3.pdf" },
            { "title": "Student Guide Book 4", "file": "pls-academy-cld-student-v2-slides-4.pdf" },
            { "title": "Student Guide Book 5", "file": "pls-academy-cld-student-v2-slides-5.pdf" },
            { "title": "Student Guide Book 6", "file": "pls-academy-cld-student-v2-slides-6.pdf" },
            { "title": "Student Guide Book 7", "file": "pls-academy-cld-student-v2-slides-7.pdf" },
            { "header": "Below notes are for Data Warehouse Session:" },
            { "title": "M0 Course Introduction", "file": "[PTI-PWDW-A]_M0_Course_Introduction.pdf" },
            { "title": "M1 Data Warehouse Solutions", "file": "[PTI-PWDW-A]_M1_Data_Warehouse_Solutions_on_Google_Cloud.pdf" },
            { "title": "M2 BigQuery for Data Warehousing", "file": "[PTI-PWDW-A]_M2_BigQuery_for_Data_Warehousing_Professionals.pdf" },
            { "title": "M3 Migrating to BigQuery", "file": "[PTI-PWDW-A]_M3_Migrating_to_BigQuery.pdf" },
            { "title": "M4 ETL Tools and Positioning", "file": "[PTI-PWDW-A]_M4_ETL_Tools_and_Positioning.pdf" },
            { "title": "M5 Streaming Analytics", "file": "[PTI-PWDW-A]_M5_Streaming_Analytics.pdf" },
            { "title": "M6 Introduction to Looker", "file": "[PTI-PWDW-A]_M6_Introduction_to_Looker_as_a_Data_Platform.pdf" },
            { "title": "M7 BigQuery Extended Capabilities", "file": "[PTI-PWDW-A]_M7_BigQuery_Extended_Capabilities.pdf" },
            { "header": "Below notes are for Apigee API Platform Session:" },
            { "title": "M0 Welcome to Apigee API Platform", "file": "M0_Welcome_to_Managing_Google_Cloud's_Apigee_API_Platform_for_Hybrid_Cloud.pdf" },
            { "title": "M1 Fundamentals", "file": "M1_Fundamentals.pdf" },
            { "title": "M2 Architecture", "file": "M2_Architecture.pdf" },
            { "title": "M3 Installation and Platform Operation", "file": "M3_Installation_and_Platform_Operation.pdf" },
            { "title": "M4 Deployment and Environment Management", "file": "M4_Deployment_and_Environment_Management.pdf" },
            { "title": "M5 Security", "file": "M5_Security.pdf" },
            { "title": "M6 Capacity Planning and Scaling", "file": "M6_Capacity_Planning_and_Scaling.pdf" },
            { "title": "M7 Upgrade", "file": "M7_Upgrade.pdf" },
            { "title": "M8 Logging and Monitoring", "file": "M8_Logging_and_Monitoring.pdf" },
            { "header": "Below notes are for Google Workspace - Work Transformation Session:" },
            { "title": "Course Introduction", "file": "Students_[PTI-PWWT-A] Course Introduction.pdf" },
            { "title": "M1 Google Workspace Customer Success Methodology", "file": "Students_[PTI-PWWT-A] M1 - Google Workspace Customer Success Methodology.pdf" },
            { "title": "M2 Provisioning", "file": "Students_[PTI-PWWT-A] M2 - Provisioning.pdf" },
            { "title": "M2.1 Lab Environment", "file": "Students_[PTI-PWWT-A] M2.1 Lab Environment - Deck.pdf" },
            { "title": "M3 System Access and Authentication", "file": "Students_[PTI-PWWT-A] M3 - System Access and Authentication.pdf" },
            { "title": "M4 Mail Routing", "file": "Students_[PTI-PWWT-A] M4 - Mail Routing.pdf" },
            { "title": "M5 Migration", "file": "Students_[PTI-PWWT-A] M5 - Migration.pdf" },
            { "title": "M6 Coexistence", "file": "Students_[PTI-PWWT-A] M6 - Coexistence.pdf" },
            { "title": "M7 Enterprise Security Overview", "file": "Students_[PTI-PWWT-A] M7 - Enterprise Security Overview.pdf" },
            { "title": "M8 Work Transformation Summary", "file": "Students_[PTI-PWWT-A] M8 - Work Transformation summary.pdf" },
            { "header": "Below notes are for Design and Manage Oracle Workloads on Google Cloud Session:" },
            { "title": "M0 Course Introduction", "file": "Delivery Copy M0_ Course Introduction (2).pdf" },
            { "title": "M2 Managed and integrated Oracle Services", "file": "Delivery Copy M2_ Managed and integrated Oracle Services.pdf" },
            { "title": "M3 Architecting Oracle solutions", "file": "Delivery Copy of M3_ Architecting Oracle solutions.pdf" },
            { "title": "M5 Design and Manage Oracle Workloads Demo", "file": "Delivery Copy of M5_ Design and Manage Oracle Workloads on Google Cloud Demo.pdf" },
            { "title": "M5 Vertex AI Coffee Demo - Hands-On Lab Guide", "file": "Delivery copy of Design and Manage Oracle Workloads on Google Cloud M5 Vertex AI Coffee Demo - Hands-On Lab Guide.pdf" },
            { "title": "M6 Resources and Q&A", "file": "Delivery Copy of M6_ Resources and Q&A (2).pdf" }
            ,
            { "header": "Below notes are for Develop apps with Conversational Agents: Lecture Notes" },
            { "title": "M0 Course Introduction", "file": "Copy of M0_ Course introduction v1.2.pdf" },
            { "title": "M1 Conversational Agents Overview", "file": "Copy of M1_ Conversational Agents overview v1.2.pdf" },
            { "title": "M2 Generative Playbooks", "file": "Copy of M2_ Generative Playbooks v1.2.pdf" },
            { "title": "M3 Virtual FAQ with data store agents", "file": "Copy of M3_ Virtual FAQ with data store agents v1.2.pdf" },
            { "title": "M4 Incorporate Generative Features", "file": "Copy of M4_ Incorporate generative features into Conversational Agent Flows v1.2.pdf" },
            { "title": "M5 Production-ready Conversational Agents", "file": "Copy of M5_ Production-ready Conversational Agents v1.2.pdf" }
        ]
    },
    "developer": {
        "title": "Professional Cloud Developer",
        "pdfs": [
            { "title": "Student Guide Book 1", "file": "pcd2.pdf" },
            { "title": "Student Guide Book 2", "file": "pcd3.pdf" },
            { "title": "Student Guide Book 3", "file": "pcd4.pdf" },
            { "title": "Student Guide Book 4", "file": "pcd5.pdf" },
            { "title": "Student Guide Book 5", "file": "pcd1.pdf" },
            { "title": "Student Guide Book 6", "file": "pcd6.pdf" },
            { "header": "Below notes are for Data Warehouse Session:" },
            { "title": "M0 Course Introduction", "file": "[PTI-PWDW-A]_M0_Course_Introduction.pdf" },
            { "title": "M1 Data Warehouse Solutions", "file": "[PTI-PWDW-A]_M1_Data_Warehouse_Solutions_on_Google_Cloud.pdf" },
            { "title": "M2 BigQuery for Data Warehousing", "file": "[PTI-PWDW-A]_M2_BigQuery_for_Data_Warehousing_Professionals.pdf" },
            { "title": "M3 Migrating to BigQuery", "file": "[PTI-PWDW-A]_M3_Migrating_to_BigQuery.pdf" },
            { "title": "M4 ETL Tools and Positioning", "file": "[PTI-PWDW-A]_M4_ETL_Tools_and_Positioning.pdf" },
            { "title": "M5 Streaming Analytics", "file": "[PTI-PWDW-A]_M5_Streaming_Analytics.pdf" },
            { "title": "M6 Introduction to Looker", "file": "[PTI-PWDW-A]_M6_Introduction_to_Looker_as_a_Data_Platform.pdf" },
            { "title": "M7 BigQuery Extended Capabilities", "file": "[PTI-PWDW-A]_M7_BigQuery_Extended_Capabilities.pdf" },
            { "header": "Below notes are for Apigee API Platform Session:" },
            { "title": "M0 Welcome to Apigee API Platform", "file": "M0_Welcome_to_Managing_Google_Cloud's_Apigee_API_Platform_for_Hybrid_Cloud.pdf" },
            { "title": "M1 Fundamentals", "file": "M1_Fundamentals.pdf" },
            { "title": "M2 Architecture", "file": "M2_Architecture.pdf" },
            { "title": "M3 Installation and Platform Operation", "file": "M3_Installation_and_Platform_Operation.pdf" },
            { "title": "M4 Deployment and Environment Management", "file": "M4_Deployment_and_Environment_Management.pdf" },
            { "title": "M5 Security", "file": "M5_Security.pdf" },
            { "title": "M6 Capacity Planning and Scaling", "file": "M6_Capacity_Planning_and_Scaling.pdf" },
            { "title": "M7 Upgrade", "file": "M7_Upgrade.pdf" },
            { "title": "M8 Logging and Monitoring", "file": "M8_Logging_and_Monitoring.pdf" },
            { "header": "Below notes are for Google Workspace - Work Transformation Session:" },
            { "title": "Course Introduction", "file": "Students_[PTI-PWWT-A] Course Introduction.pdf" },
            { "title": "M1 Google Workspace Customer Success Methodology", "file": "Students_[PTI-PWWT-A] M1 - Google Workspace Customer Success Methodology.pdf" },
            { "title": "M2 Provisioning", "file": "Students_[PTI-PWWT-A] M2 - Provisioning.pdf" },
            { "title": "M2.1 Lab Environment", "file": "Students_[PTI-PWWT-A] M2.1 Lab Environment - Deck.pdf" },
            { "title": "M3 System Access and Authentication", "file": "Students_[PTI-PWWT-A] M3 - System Access and Authentication.pdf" },
            { "title": "M4 Mail Routing", "file": "Students_[PTI-PWWT-A] M4 - Mail Routing.pdf" },
            { "title": "M5 Migration", "file": "Students_[PTI-PWWT-A] M5 - Migration.pdf" },
            { "title": "M6 Coexistence", "file": "Students_[PTI-PWWT-A] M6 - Coexistence.pdf" },
            { "title": "M7 Enterprise Security Overview", "file": "Students_[PTI-PWWT-A] M7 - Enterprise Security Overview.pdf" },
            { "title": "M8 Work Transformation Summary", "file": "Students_[PTI-PWWT-A] M8 - Work Transformation summary.pdf" }
            ,
            { "header": "Below notes are for Develop apps with Conversational Agents: Lecture Notes" },
            { "title": "M0 Course Introduction", "file": "Copy of M0_ Course introduction v1.2.pdf" },
            { "title": "M1 Conversational Agents Overview", "file": "Copy of M1_ Conversational Agents overview v1.2.pdf" },
            { "title": "M2 Generative Playbooks", "file": "Copy of M2_ Generative Playbooks v1.2.pdf" },
            { "title": "M3 Virtual FAQ with data store agents", "file": "Copy of M3_ Virtual FAQ with data store agents v1.2.pdf" },
            { "title": "M4 Incorporate Generative Features", "file": "Copy of M4_ Incorporate generative features into Conversational Agent Flows v1.2.pdf" },
            { "title": "M5 Production-ready Conversational Agents", "file": "Copy of M5_ Production-ready Conversational Agents v1.2.pdf" }
        ]
    },
    "ml-engineer": {
        "title": "Professional Machine Learning Engineer",
        "pdfs": [
            { "title": "Student Guide Book 1", "file": "pls-academy-pmle-student-slides-1-2403.pdf" },
            { "title": "Student Guide Book 2", "file": "pls-academy-pmle-student-slides-2-2403.pdf" },
            { "title": "Student Guide Book 3", "file": "pls-academy-pmle-student-slides-3-2403.pdf" },
            { "title": "Student Guide Book 4", "file": "pls-academy-pmle-student-slides-4-2403.pdf" },
            { "title": "Student Guide Book 5", "file": "pls-academy-pmle-student-slides-5-2403.pdf" },
            { "title": "Student Guide Book 6", "file": "pls-academy-pmle-student-slides-6-2403.pdf" },
            { "title": "Student Guide Book 7", "file": "pls-academy-pmle-student-slides-7-2403.pdf" },
            { "title": "Student Guide Book 8", "file": "pls-academy-pmle-student-slides-8-2403.pdf" },
            { "title": "Student Guide Book 9", "file": "pls-academy-pmle-student-slides-9-2403.pdf" },
            { "header": "Below notes are for Data Warehouse Session:" },
            { "title": "M0 Course Introduction", "file": "[PTI-PWDW-A]_M0_Course_Introduction.pdf" },
            { "title": "M1 Data Warehouse Solutions", "file": "[PTI-PWDW-A]_M1_Data_Warehouse_Solutions_on_Google_Cloud.pdf" },
            { "title": "M2 BigQuery for Data Warehousing", "file": "[PTI-PWDW-A]_M2_BigQuery_for_Data_Warehousing_Professionals.pdf" },
            { "title": "M3 Migrating to BigQuery", "file": "[PTI-PWDW-A]_M3_Migrating_to_BigQuery.pdf" },
            { "title": "M4 ETL Tools and Positioning", "file": "[PTI-PWDW-A]_M4_ETL_Tools_and_Positioning.pdf" },
            { "title": "M5 Streaming Analytics", "file": "[PTI-PWDW-A]_M5_Streaming_Analytics.pdf" },
            { "title": "M6 Introduction to Looker", "file": "[PTI-PWDW-A]_M6_Introduction_to_Looker_as_a_Data_Platform.pdf" },
            { "title": "M7 BigQuery Extended Capabilities", "file": "[PTI-PWDW-A]_M7_BigQuery_Extended_Capabilities.pdf" },
            { "header": "Below notes are for Apigee API Platform Session:" },
            { "title": "M0 Welcome to Apigee API Platform", "file": "M0_Welcome_to_Managing_Google_Cloud's_Apigee_API_Platform_for_Hybrid_Cloud.pdf" },
            { "title": "M1 Fundamentals", "file": "M1_Fundamentals.pdf" },
            { "title": "M2 Architecture", "file": "M2_Architecture.pdf" },
            { "title": "M3 Installation and Platform Operation", "file": "M3_Installation_and_Platform_Operation.pdf" },
            { "title": "M4 Deployment and Environment Management", "file": "M4_Deployment_and_Environment_Management.pdf" },
            { "title": "M5 Security", "file": "M5_Security.pdf" },
            { "title": "M6 Capacity Planning and Scaling", "file": "M6_Capacity_Planning_and_Scaling.pdf" },
            { "title": "M7 Upgrade", "file": "M7_Upgrade.pdf" },
            { "title": "M8 Logging and Monitoring", "file": "M8_Logging_and_Monitoring.pdf" },
            { "header": "Below notes are for Google Workspace - Work Transformation Session:" },
            { "title": "Course Introduction", "file": "Students_[PTI-PWWT-A] Course Introduction.pdf" },
            { "title": "M1 Google Workspace Customer Success Methodology", "file": "Students_[PTI-PWWT-A] M1 - Google Workspace Customer Success Methodology.pdf" },
            { "title": "M2 Provisioning", "file": "Students_[PTI-PWWT-A] M2 - Provisioning.pdf" },
            { "title": "M2.1 Lab Environment", "file": "Students_[PTI-PWWT-A] M2.1 Lab Environment - Deck.pdf" },
            { "title": "M3 System Access and Authentication", "file": "Students_[PTI-PWWT-A] M3 - System Access and Authentication.pdf" },
            { "title": "M4 Mail Routing", "file": "Students_[PTI-PWWT-A] M4 - Mail Routing.pdf" },
            { "title": "M5 Migration", "file": "Students_[PTI-PWWT-A] M5 - Migration.pdf" },
            { "title": "M6 Coexistence", "file": "Students_[PTI-PWWT-A] M6 - Coexistence.pdf" },
            { "title": "M7 Enterprise Security Overview", "file": "Students_[PTI-PWWT-A] M7 - Enterprise Security Overview.pdf" },
            { "title": "M8 Work Transformation Summary", "file": "Students_[PTI-PWWT-A] M8 - Work Transformation summary.pdf" }
            ,
            { "header": "Below notes are for Develop apps with Conversational Agents: Lecture Notes" },
            { "title": "M0 Course Introduction", "file": "Copy of M0_ Course introduction v1.2.pdf" },
            { "title": "M1 Conversational Agents Overview", "file": "Copy of M1_ Conversational Agents overview v1.2.pdf" },
            { "title": "M2 Generative Playbooks", "file": "Copy of M2_ Generative Playbooks v1.2.pdf" },
            { "title": "M3 Virtual FAQ with data store agents", "file": "Copy of M3_ Virtual FAQ with data store agents v1.2.pdf" },
            { "title": "M4 Incorporate Generative Features", "file": "Copy of M4_ Incorporate generative features into Conversational Agent Flows v1.2.pdf" },
            { "title": "M5 Production-ready Conversational Agents", "file": "Copy of M5_ Production-ready Conversational Agents v1.2.pdf" }
        ]
    },
    "gen-ai": {
        "title": "Generative AI",
        "pdfs": [
            { "title": "Student Guide Book 1", "file": "gen-ai-notes.pdf" },
            { "header": "Below notes are for Data Warehouse Session:" },
            { "title": "M0 Course Introduction", "file": "[PTI-PWDW-A]_M0_Course_Introduction.pdf" },
            { "title": "M1 Data Warehouse Solutions", "file": "[PTI-PWDW-A]_M1_Data_Warehouse_Solutions_on_Google_Cloud.pdf" },
            { "title": "M2 BigQuery for Data Warehousing", "file": "[PTI-PWDW-A]_M2_BigQuery_for_Data_Warehousing_Professionals.pdf" },
            { "title": "M3 Migrating to BigQuery", "file": "[PTI-PWDW-A]_M3_Migrating_to_BigQuery.pdf" },
            { "title": "M4 ETL Tools and Positioning", "file": "[PTI-PWDW-A]_M4_ETL_Tools_and_Positioning.pdf" },
            { "title": "M5 Streaming Analytics", "file": "[PTI-PWDW-A]_M5_Streaming_Analytics.pdf" },
            { "title": "M6 Introduction to Looker", "file": "[PTI-PWDW-A]_M6_Introduction_to_Looker_as_a_Data_Platform.pdf" },
            { "title": "M7 BigQuery Extended Capabilities", "file": "[PTI-PWDW-A]_M7_BigQuery_Extended_Capabilities.pdf" },
            { "header": "Below notes are for Apigee API Platform Session:" },
            { "title": "M0 Welcome to Apigee API Platform", "file": "M0_Welcome_to_Managing_Google_Cloud's_Apigee_API_Platform_for_Hybrid_Cloud.pdf" },
            { "title": "M1 Fundamentals", "file": "M1_Fundamentals.pdf" },
            { "title": "M2 Architecture", "file": "M2_Architecture.pdf" },
            { "title": "M3 Installation and Platform Operation", "file": "M3_Installation_and_Platform_Operation.pdf" },
            { "title": "M4 Deployment and Environment Management", "file": "M4_Deployment_and_Environment_Management.pdf" },
            { "title": "M5 Security", "file": "M5_Security.pdf" },
            { "title": "M6 Capacity Planning and Scaling", "file": "M6_Capacity_Planning_and_Scaling.pdf" },
            { "title": "M7 Upgrade", "file": "M7_Upgrade.pdf" },
            { "title": "M8 Logging and Monitoring", "file": "M8_Logging_and_Monitoring.pdf" },
            { "header": "Below notes are for Google Workspace - Work Transformation Session:" },
            { "title": "Course Introduction", "file": "Students_[PTI-PWWT-A] Course Introduction.pdf" },
            { "title": "M1 Google Workspace Customer Success Methodology", "file": "Students_[PTI-PWWT-A] M1 - Google Workspace Customer Success Methodology.pdf" },
            { "title": "M2 Provisioning", "file": "Students_[PTI-PWWT-A] M2 - Provisioning.pdf" },
            { "title": "M2.1 Lab Environment", "file": "Students_[PTI-PWWT-A] M2.1 Lab Environment - Deck.pdf" },
            { "title": "M3 System Access and Authentication", "file": "Students_[PTI-PWWT-A] M3 - System Access and Authentication.pdf" },
            { "title": "M4 Mail Routing", "file": "Students_[PTI-PWWT-A] M4 - Mail Routing.pdf" },
            { "title": "M5 Migration", "file": "Students_[PTI-PWWT-A] M5 - Migration.pdf" },
            { "title": "M6 Coexistence", "file": "Students_[PTI-PWWT-A] M6 - Coexistence.pdf" },
            { "title": "M7 Enterprise Security Overview", "file": "Students_[PTI-PWWT-A] M7 - Enterprise Security Overview.pdf" },
            { "title": "M8 Work Transformation Summary", "file": "Students_[PTI-PWWT-A] M8 - Work Transformation summary.pdf" }
            ,
            { "header": "Below notes are for Develop apps with Conversational Agents: Lecture Notes" },
            { "title": "M0 Course Introduction", "file": "Copy of M0_ Course introduction v1.2.pdf" },
            { "title": "M1 Conversational Agents Overview", "file": "Copy of M1_ Conversational Agents overview v1.2.pdf" },
            { "title": "M2 Generative Playbooks", "file": "Copy of M2_ Generative Playbooks v1.2.pdf" },
            { "title": "M3 Virtual FAQ with data store agents", "file": "Copy of M3_ Virtual FAQ with data store agents v1.2.pdf" },
            { "title": "M4 Incorporate Generative Features", "file": "Copy of M4_ Incorporate generative features into Conversational Agent Flows v1.2.pdf" },
            { "title": "M5 Production-ready Conversational Agents", "file": "Copy of M5_ Production-ready Conversational Agents v1.2.pdf" }
        ]
    },
    "exam-readiness": {
        "title": "Exam Readiness Workshop",
        "pdfs": [
            { "title": "Student Guide Book 1", "file": "pls-erw-ace-student-slides-1-2309.pdf" },
            { "title": "Exam Readiness Guide", "file": "exam-readyness.pdf" },
            { "header": "Below notes are for Data Warehouse Session:" },
            { "title": "M0 Course Introduction", "file": "[PTI-PWDW-A]_M0_Course_Introduction.pdf" },
            { "title": "M1 Data Warehouse Solutions", "file": "[PTI-PWDW-A]_M1_Data_Warehouse_Solutions_on_Google_Cloud.pdf" },
            { "title": "M2 BigQuery for Data Warehousing", "file": "[PTI-PWDW-A]_M2_BigQuery_for_Data_Warehousing_Professionals.pdf" },
            { "title": "M3 Migrating to BigQuery", "file": "[PTI-PWDW-A]_M3_Migrating_to_BigQuery.pdf" },
            { "title": "M4 ETL Tools and Positioning", "file": "[PTI-PWDW-A]_M4_ETL_Tools_and_Positioning.pdf" },
            { "title": "M5 Streaming Analytics", "file": "[PTI-PWDW-A]_M5_Streaming_Analytics.pdf" },
            { "title": "M6 Introduction to Looker", "file": "[PTI-PWDW-A]_M6_Introduction_to_Looker_as_a_Data_Platform.pdf" },
            { "title": "M7 BigQuery Extended Capabilities", "file": "[PTI-PWDW-A]_M7_BigQuery_Extended_Capabilities.pdf" },
            { "header": "Below notes are for Apigee API Platform Session:" },
            { "title": "M0 Welcome to Apigee API Platform", "file": "M0_Welcome_to_Managing_Google_Cloud's_Apigee_API_Platform_for_Hybrid_Cloud.pdf" },
            { "title": "M1 Fundamentals", "file": "M1_Fundamentals.pdf" },
            { "title": "M2 Architecture", "file": "M2_Architecture.pdf" },
            { "title": "M3 Installation and Platform Operation", "file": "M3_Installation_and_Platform_Operation.pdf" },
            { "title": "M4 Deployment and Environment Management", "file": "M4_Deployment_and_Environment_Management.pdf" },
            { "title": "M5 Security", "file": "M5_Security.pdf" },
            { "title": "M6 Capacity Planning and Scaling", "file": "M6_Capacity_Planning_and_Scaling.pdf" },
            { "title": "M7 Upgrade", "file": "M7_Upgrade.pdf" },
            { "title": "M8 Logging and Monitoring", "file": "M8_Logging_and_Monitoring.pdf" },
            { "header": "Below notes are for Google Workspace - Work Transformation Session:" },
            { "title": "Course Introduction", "file": "Students_[PTI-PWWT-A] Course Introduction.pdf" },
            { "title": "M1 Google Workspace Customer Success Methodology", "file": "Students_[PTI-PWWT-A] M1 - Google Workspace Customer Success Methodology.pdf" },
            { "title": "M2 Provisioning", "file": "Students_[PTI-PWWT-A] M2 - Provisioning.pdf" },
            { "title": "M2.1 Lab Environment", "file": "Students_[PTI-PWWT-A] M2.1 Lab Environment - Deck.pdf" },
            { "title": "M3 System Access and Authentication", "file": "Students_[PTI-PWWT-A] M3 - System Access and Authentication.pdf" },
            { "title": "M4 Mail Routing", "file": "Students_[PTI-PWWT-A] M4 - Mail Routing.pdf" },
            { "title": "M5 Migration", "file": "Students_[PTI-PWWT-A] M5 - Migration.pdf" },
            { "title": "M6 Coexistence", "file": "Students_[PTI-PWWT-A] M6 - Coexistence.pdf" },
            { "title": "M7 Enterprise Security Overview", "file": "Students_[PTI-PWWT-A] M7 - Enterprise Security Overview.pdf" },
            { "title": "M8 Work Transformation Summary", "file": "Students_[PTI-PWWT-A] M8 - Work Transformation summary.pdf" }
            ,
            { "header": "Below notes are for Develop apps with Conversational Agents: Lecture Notes" },
            { "title": "M0 Course Introduction", "file": "Copy of M0_ Course introduction v1.2.pdf" },
            { "title": "M1 Conversational Agents Overview", "file": "Copy of M1_ Conversational Agents overview v1.2.pdf" },
            { "title": "M2 Generative Playbooks", "file": "Copy of M2_ Generative Playbooks v1.2.pdf" },
            { "title": "M3 Virtual FAQ with data store agents", "file": "Copy of M3_ Virtual FAQ with data store agents v1.2.pdf" },
            { "title": "M4 Incorporate Generative Features", "file": "Copy of M4_ Incorporate generative features into Conversational Agent Flows v1.2.pdf" },
            { "title": "M5 Production-ready Conversational Agents", "file": "Copy of M5_ Production-ready Conversational Agents v1.2.pdf" }
        ]
    }
};
